import type { Metadata } from "next";
import { Inter } from 'next/font/google'
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";

const font = Inter({ subsets: ['latin'], weight: '500' });

export const metadata: Metadata = {
  title: "Result Management",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${font.className} antialiased`}
      >
        <ClerkProvider>
          {children}</ClerkProvider>
      </body>
    </html>
  );
}
